#!/bin/sh

RPI=root@10.42.0.65 # Make sure to change this to the actual ip on your RPI4

# Check if exactly four parameters are provided
if [ $# -ne 4 ]; then
    echo "Usage: $0 <milisecs> <hamming> <measurements> <sampling>"
    exit 1
fi

milisecs="$1"
hamming="$2"
measurements="$3"
sampling="$4"

sshpass -p '1234' ssh  -t ${RPI} "cd /test ; chmod +x run_covert_channel ;./run_covert_channel $milisecs $hamming $measurements $sampling"