#!/bin/sh

RPI=root@10.42.0.65

# Check if exactly two parameters are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <milisecs> <hamming>"
    exit 1
fi

milisecs="$1"
hamming="$2"

sshpass -p '1234' ssh  -t ${RPI} "cd /test ; chmod +x run_covert_channel ;./run_covert_channel $milisecs $hamming"