#!/bin/sh

# Check if at least one parameter is provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <parameter>"
    exit 1
fi

parameter="$1"

echo "Hello from BusyBox!"
echo "Today's date is $(date)"
echo "Parameter passed to the script: $parameter"
